### ISSUE TITLE
Only include English posts in RSS feeds

### ISSUE THREAD

**Issue by j-f1** [gaearon/overreacted.io#72]
I was excited to get a new Overreacted post in my RSS reader this morning, but discovered that it was a translation of an existing post. Would it be possible to skip translated posts when building the RSS feed?

Note to self 📝
- make sure lang is in `<html>`
- filter list of posts in config file

**Comment by gaearon** [comment]
Yeah but I don't know how. :D 
Happy to take a PR.

**Comment by AndrewIngram** [comment]
You just need to add a filter to this query: https://github.com/gaearon/overreacted.io/blob/master/gatsby-config.js#L104-L107

Gimme a min.

**Comment by AndrewIngram** [comment]
Okay, it looks like you've got each translation included all the languages in its langs (which is great, because you can properly do some page metadata), but you need a way identifying the language of an individual translation. There are two ways to do this:

1. You can filter on `fileAbsolutePath` and use a regex to exclude anything which has a language suffix, eg `.tr.md`. This will work with the way things are now.

2. Add a new frontmatter field representing the language, sitting alongside the existing `langs` field.

The second is a bit better in my eyes, but more work.
